### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by t8ert0t** [dagrha/pypia#7] opened 2017-01-27 00:48 UTC
Whenever I try to run a script, terminal outputs the following:

`./install_lubuntu.sh: 6: ./install_lubuntu.sh: Syntax error: newline unexpected`

**Comment by dagrha** [comment] 2017-01-27 17:05
Thanks for the comment. I will take a peek at this issue over the weekend to see if I can fix it.

**Comment by dagrha** [comment] 2017-01-29 00:17
Hi @t8ert0t, I was not able to reproduce this error on a virtual machine instance of lubuntu 16.10. What version of lubuntu are you using? Are you running the script as described in the [readme](https://github.com/dagrha/PIA_install_scripts/blob/master/README.md)?

**Comment by t8ert0t** [comment] 2017-01-29 00:29
Hey Dan.

Was actually thinking Linux Mint 18. Tried both the Ubuntu and Lubuntu
script just to see if it'd would work because they're usually not that
different.

**Comment by dagrha** [comment] 2017-01-29 16:21
Sorry @t8ert0t, I tried it on the latest Linux Mint 18 in a virtual machine and was unable to reproduce the error. ![Here's screen cap of the successful install](https://cloud.githubusercontent.com/assets/6957654/22405700/c388df34-e603-11e6-9902-1baf079ea9bc.png)

I wish I could help more but unless there is something I can reproduce there's not much I can do... If you end up being able to fix the issue, please consider submitting a pull request! Thanks.

**Comment by dagrha** [comment] 2017-02-01 20:50
Going to close this issue for now since I can't reproduce it, but if others run into this issue please re-open.

**Closed as completed by dagrha** 2017-02-01 20:50 UTC
